/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosGraduacaoOficialRouteImport } from './routes/pos-graduacao-oficial'
import { Route as PosGraduacaoAnestesiaObstetricaRouteImport } from './routes/pos-graduacao-anestesia-obstetrica'
import { Route as PosGraduacaoRouteImport } from './routes/pos-graduacao'
import { Route as LiveSecretaPolemicasRouteImport } from './routes/live-secreta-polemicas'
import { Route as LiveSecretaObgRouteImport } from './routes/live-secreta-obg'
import { Route as LiveSecretaRouteImport } from './routes/live-secreta'
import { Route as FisiologiaFarmacologiaRouteImport } from './routes/fisiologia-farmacologia'
import { Route as EbookViasaereasObgRouteImport } from './routes/ebook-viasaereas-obg'
import { Route as EbookViasAereasRouteImport } from './routes/ebook-vias-aereas'
import { Route as EbookVasoativoObgRouteImport } from './routes/ebook-vasoativo-obg'
import { Route as EbookVasoativoRouteImport } from './routes/ebook-vasoativo'
import { Route as CongressoRouteImport } from './routes/congresso'
import { Route as BonusPosRouteImport } from './routes/bonus-pos'
import { Route as IndexRouteImport } from './routes/index'

const PosGraduacaoOficialRoute = PosGraduacaoOficialRouteImport.update({
  id: '/pos-graduacao-oficial',
  path: '/pos-graduacao-oficial',
  getParentRoute: () => rootRouteImport,
} as any)
const PosGraduacaoAnestesiaObstetricaRoute =
  PosGraduacaoAnestesiaObstetricaRouteImport.update({
    id: '/pos-graduacao-anestesia-obstetrica',
    path: '/pos-graduacao-anestesia-obstetrica',
    getParentRoute: () => rootRouteImport,
  } as any)
const PosGraduacaoRoute = PosGraduacaoRouteImport.update({
  id: '/pos-graduacao',
  path: '/pos-graduacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSecretaPolemicasRoute = LiveSecretaPolemicasRouteImport.update({
  id: '/live-secreta-polemicas',
  path: '/live-secreta-polemicas',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSecretaObgRoute = LiveSecretaObgRouteImport.update({
  id: '/live-secreta-obg',
  path: '/live-secreta-obg',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSecretaRoute = LiveSecretaRouteImport.update({
  id: '/live-secreta',
  path: '/live-secreta',
  getParentRoute: () => rootRouteImport,
} as any)
const FisiologiaFarmacologiaRoute = FisiologiaFarmacologiaRouteImport.update({
  id: '/fisiologia-farmacologia',
  path: '/fisiologia-farmacologia',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookViasaereasObgRoute = EbookViasaereasObgRouteImport.update({
  id: '/ebook-viasaereas-obg',
  path: '/ebook-viasaereas-obg',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookViasAereasRoute = EbookViasAereasRouteImport.update({
  id: '/ebook-vias-aereas',
  path: '/ebook-vias-aereas',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookVasoativoObgRoute = EbookVasoativoObgRouteImport.update({
  id: '/ebook-vasoativo-obg',
  path: '/ebook-vasoativo-obg',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookVasoativoRoute = EbookVasoativoRouteImport.update({
  id: '/ebook-vasoativo',
  path: '/ebook-vasoativo',
  getParentRoute: () => rootRouteImport,
} as any)
const CongressoRoute = CongressoRouteImport.update({
  id: '/congresso',
  path: '/congresso',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusPosRoute = BonusPosRouteImport.update({
  id: '/bonus-pos',
  path: '/bonus-pos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bonus-pos': typeof BonusPosRoute
  '/congresso': typeof CongressoRoute
  '/ebook-vasoativo': typeof EbookVasoativoRoute
  '/ebook-vasoativo-obg': typeof EbookVasoativoObgRoute
  '/ebook-vias-aereas': typeof EbookViasAereasRoute
  '/ebook-viasaereas-obg': typeof EbookViasaereasObgRoute
  '/fisiologia-farmacologia': typeof FisiologiaFarmacologiaRoute
  '/live-secreta': typeof LiveSecretaRoute
  '/live-secreta-obg': typeof LiveSecretaObgRoute
  '/live-secreta-polemicas': typeof LiveSecretaPolemicasRoute
  '/pos-graduacao': typeof PosGraduacaoRoute
  '/pos-graduacao-anestesia-obstetrica': typeof PosGraduacaoAnestesiaObstetricaRoute
  '/pos-graduacao-oficial': typeof PosGraduacaoOficialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bonus-pos': typeof BonusPosRoute
  '/congresso': typeof CongressoRoute
  '/ebook-vasoativo': typeof EbookVasoativoRoute
  '/ebook-vasoativo-obg': typeof EbookVasoativoObgRoute
  '/ebook-vias-aereas': typeof EbookViasAereasRoute
  '/ebook-viasaereas-obg': typeof EbookViasaereasObgRoute
  '/fisiologia-farmacologia': typeof FisiologiaFarmacologiaRoute
  '/live-secreta': typeof LiveSecretaRoute
  '/live-secreta-obg': typeof LiveSecretaObgRoute
  '/live-secreta-polemicas': typeof LiveSecretaPolemicasRoute
  '/pos-graduacao': typeof PosGraduacaoRoute
  '/pos-graduacao-anestesia-obstetrica': typeof PosGraduacaoAnestesiaObstetricaRoute
  '/pos-graduacao-oficial': typeof PosGraduacaoOficialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bonus-pos': typeof BonusPosRoute
  '/congresso': typeof CongressoRoute
  '/ebook-vasoativo': typeof EbookVasoativoRoute
  '/ebook-vasoativo-obg': typeof EbookVasoativoObgRoute
  '/ebook-vias-aereas': typeof EbookViasAereasRoute
  '/ebook-viasaereas-obg': typeof EbookViasaereasObgRoute
  '/fisiologia-farmacologia': typeof FisiologiaFarmacologiaRoute
  '/live-secreta': typeof LiveSecretaRoute
  '/live-secreta-obg': typeof LiveSecretaObgRoute
  '/live-secreta-polemicas': typeof LiveSecretaPolemicasRoute
  '/pos-graduacao': typeof PosGraduacaoRoute
  '/pos-graduacao-anestesia-obstetrica': typeof PosGraduacaoAnestesiaObstetricaRoute
  '/pos-graduacao-oficial': typeof PosGraduacaoOficialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bonus-pos'
    | '/congresso'
    | '/ebook-vasoativo'
    | '/ebook-vasoativo-obg'
    | '/ebook-vias-aereas'
    | '/ebook-viasaereas-obg'
    | '/fisiologia-farmacologia'
    | '/live-secreta'
    | '/live-secreta-obg'
    | '/live-secreta-polemicas'
    | '/pos-graduacao'
    | '/pos-graduacao-anestesia-obstetrica'
    | '/pos-graduacao-oficial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bonus-pos'
    | '/congresso'
    | '/ebook-vasoativo'
    | '/ebook-vasoativo-obg'
    | '/ebook-vias-aereas'
    | '/ebook-viasaereas-obg'
    | '/fisiologia-farmacologia'
    | '/live-secreta'
    | '/live-secreta-obg'
    | '/live-secreta-polemicas'
    | '/pos-graduacao'
    | '/pos-graduacao-anestesia-obstetrica'
    | '/pos-graduacao-oficial'
  id:
    | '__root__'
    | '/'
    | '/bonus-pos'
    | '/congresso'
    | '/ebook-vasoativo'
    | '/ebook-vasoativo-obg'
    | '/ebook-vias-aereas'
    | '/ebook-viasaereas-obg'
    | '/fisiologia-farmacologia'
    | '/live-secreta'
    | '/live-secreta-obg'
    | '/live-secreta-polemicas'
    | '/pos-graduacao'
    | '/pos-graduacao-anestesia-obstetrica'
    | '/pos-graduacao-oficial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BonusPosRoute: typeof BonusPosRoute
  CongressoRoute: typeof CongressoRoute
  EbookVasoativoRoute: typeof EbookVasoativoRoute
  EbookVasoativoObgRoute: typeof EbookVasoativoObgRoute
  EbookViasAereasRoute: typeof EbookViasAereasRoute
  EbookViasaereasObgRoute: typeof EbookViasaereasObgRoute
  FisiologiaFarmacologiaRoute: typeof FisiologiaFarmacologiaRoute
  LiveSecretaRoute: typeof LiveSecretaRoute
  LiveSecretaObgRoute: typeof LiveSecretaObgRoute
  LiveSecretaPolemicasRoute: typeof LiveSecretaPolemicasRoute
  PosGraduacaoRoute: typeof PosGraduacaoRoute
  PosGraduacaoAnestesiaObstetricaRoute: typeof PosGraduacaoAnestesiaObstetricaRoute
  PosGraduacaoOficialRoute: typeof PosGraduacaoOficialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pos-graduacao-oficial': {
      id: '/pos-graduacao-oficial'
      path: '/pos-graduacao-oficial'
      fullPath: '/pos-graduacao-oficial'
      preLoaderRoute: typeof PosGraduacaoOficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-graduacao-anestesia-obstetrica': {
      id: '/pos-graduacao-anestesia-obstetrica'
      path: '/pos-graduacao-anestesia-obstetrica'
      fullPath: '/pos-graduacao-anestesia-obstetrica'
      preLoaderRoute: typeof PosGraduacaoAnestesiaObstetricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-graduacao': {
      id: '/pos-graduacao'
      path: '/pos-graduacao'
      fullPath: '/pos-graduacao'
      preLoaderRoute: typeof PosGraduacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-secreta-polemicas': {
      id: '/live-secreta-polemicas'
      path: '/live-secreta-polemicas'
      fullPath: '/live-secreta-polemicas'
      preLoaderRoute: typeof LiveSecretaPolemicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-secreta-obg': {
      id: '/live-secreta-obg'
      path: '/live-secreta-obg'
      fullPath: '/live-secreta-obg'
      preLoaderRoute: typeof LiveSecretaObgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-secreta': {
      id: '/live-secreta'
      path: '/live-secreta'
      fullPath: '/live-secreta'
      preLoaderRoute: typeof LiveSecretaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fisiologia-farmacologia': {
      id: '/fisiologia-farmacologia'
      path: '/fisiologia-farmacologia'
      fullPath: '/fisiologia-farmacologia'
      preLoaderRoute: typeof FisiologiaFarmacologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-viasaereas-obg': {
      id: '/ebook-viasaereas-obg'
      path: '/ebook-viasaereas-obg'
      fullPath: '/ebook-viasaereas-obg'
      preLoaderRoute: typeof EbookViasaereasObgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-vias-aereas': {
      id: '/ebook-vias-aereas'
      path: '/ebook-vias-aereas'
      fullPath: '/ebook-vias-aereas'
      preLoaderRoute: typeof EbookViasAereasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-vasoativo-obg': {
      id: '/ebook-vasoativo-obg'
      path: '/ebook-vasoativo-obg'
      fullPath: '/ebook-vasoativo-obg'
      preLoaderRoute: typeof EbookVasoativoObgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-vasoativo': {
      id: '/ebook-vasoativo'
      path: '/ebook-vasoativo'
      fullPath: '/ebook-vasoativo'
      preLoaderRoute: typeof EbookVasoativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congresso': {
      id: '/congresso'
      path: '/congresso'
      fullPath: '/congresso'
      preLoaderRoute: typeof CongressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus-pos': {
      id: '/bonus-pos'
      path: '/bonus-pos'
      fullPath: '/bonus-pos'
      preLoaderRoute: typeof BonusPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BonusPosRoute: BonusPosRoute,
  CongressoRoute: CongressoRoute,
  EbookVasoativoRoute: EbookVasoativoRoute,
  EbookVasoativoObgRoute: EbookVasoativoObgRoute,
  EbookViasAereasRoute: EbookViasAereasRoute,
  EbookViasaereasObgRoute: EbookViasaereasObgRoute,
  FisiologiaFarmacologiaRoute: FisiologiaFarmacologiaRoute,
  LiveSecretaRoute: LiveSecretaRoute,
  LiveSecretaObgRoute: LiveSecretaObgRoute,
  LiveSecretaPolemicasRoute: LiveSecretaPolemicasRoute,
  PosGraduacaoRoute: PosGraduacaoRoute,
  PosGraduacaoAnestesiaObstetricaRoute: PosGraduacaoAnestesiaObstetricaRoute,
  PosGraduacaoOficialRoute: PosGraduacaoOficialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
