/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FisiologiaFarmacologiaRouteImport } from './routes/fisiologia-farmacologia'
import { Route as EbookVasoativoObgRouteImport } from './routes/ebook-vasoativo-obg'
import { Route as EbookVasoativoRouteImport } from './routes/ebook-vasoativo'
import { Route as CongressoRouteImport } from './routes/congresso'
import { Route as IndexRouteImport } from './routes/index'

const FisiologiaFarmacologiaRoute = FisiologiaFarmacologiaRouteImport.update({
  id: '/fisiologia-farmacologia',
  path: '/fisiologia-farmacologia',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookVasoativoObgRoute = EbookVasoativoObgRouteImport.update({
  id: '/ebook-vasoativo-obg',
  path: '/ebook-vasoativo-obg',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookVasoativoRoute = EbookVasoativoRouteImport.update({
  id: '/ebook-vasoativo',
  path: '/ebook-vasoativo',
  getParentRoute: () => rootRouteImport,
} as any)
const CongressoRoute = CongressoRouteImport.update({
  id: '/congresso',
  path: '/congresso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/congresso': typeof CongressoRoute
  '/ebook-vasoativo': typeof EbookVasoativoRoute
  '/ebook-vasoativo-obg': typeof EbookVasoativoObgRoute
  '/fisiologia-farmacologia': typeof FisiologiaFarmacologiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/congresso': typeof CongressoRoute
  '/ebook-vasoativo': typeof EbookVasoativoRoute
  '/ebook-vasoativo-obg': typeof EbookVasoativoObgRoute
  '/fisiologia-farmacologia': typeof FisiologiaFarmacologiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/congresso': typeof CongressoRoute
  '/ebook-vasoativo': typeof EbookVasoativoRoute
  '/ebook-vasoativo-obg': typeof EbookVasoativoObgRoute
  '/fisiologia-farmacologia': typeof FisiologiaFarmacologiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/congresso'
    | '/ebook-vasoativo'
    | '/ebook-vasoativo-obg'
    | '/fisiologia-farmacologia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/congresso'
    | '/ebook-vasoativo'
    | '/ebook-vasoativo-obg'
    | '/fisiologia-farmacologia'
  id:
    | '__root__'
    | '/'
    | '/congresso'
    | '/ebook-vasoativo'
    | '/ebook-vasoativo-obg'
    | '/fisiologia-farmacologia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CongressoRoute: typeof CongressoRoute
  EbookVasoativoRoute: typeof EbookVasoativoRoute
  EbookVasoativoObgRoute: typeof EbookVasoativoObgRoute
  FisiologiaFarmacologiaRoute: typeof FisiologiaFarmacologiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fisiologia-farmacologia': {
      id: '/fisiologia-farmacologia'
      path: '/fisiologia-farmacologia'
      fullPath: '/fisiologia-farmacologia'
      preLoaderRoute: typeof FisiologiaFarmacologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-vasoativo-obg': {
      id: '/ebook-vasoativo-obg'
      path: '/ebook-vasoativo-obg'
      fullPath: '/ebook-vasoativo-obg'
      preLoaderRoute: typeof EbookVasoativoObgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-vasoativo': {
      id: '/ebook-vasoativo'
      path: '/ebook-vasoativo'
      fullPath: '/ebook-vasoativo'
      preLoaderRoute: typeof EbookVasoativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congresso': {
      id: '/congresso'
      path: '/congresso'
      fullPath: '/congresso'
      preLoaderRoute: typeof CongressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CongressoRoute: CongressoRoute,
  EbookVasoativoRoute: EbookVasoativoRoute,
  EbookVasoativoObgRoute: EbookVasoativoObgRoute,
  FisiologiaFarmacologiaRoute: FisiologiaFarmacologiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
