CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE TABLE public.quiz_sessions (
  session_id uuid PRIMARY KEY,
  quiz_slug text NOT NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  last_activity_at timestamptz NOT NULL DEFAULT now(),
  last_question_reached smallint NOT NULL DEFAULT 1 CHECK (last_question_reached BETWEEN 1 AND 7),
  completed_at timestamptz,
  score smallint CHECK (score BETWEEN 0 AND 7),
  CONSTRAINT quiz_sessions_slug_check CHECK (quiz_slug = 'quiz-aula-magna'),
  CONSTRAINT quiz_sessions_completion_check CHECK ((completed_at IS NULL AND score IS NULL) OR (completed_at IS NOT NULL AND score IS NOT NULL))
);
GRANT ALL ON public.quiz_sessions TO service_role;
ALTER TABLE public.quiz_sessions ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.quiz_answers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid NOT NULL REFERENCES public.quiz_sessions(session_id) ON DELETE CASCADE,
  quiz_slug text NOT NULL,
  question_number smallint NOT NULL CHECK (question_number BETWEEN 1 AND 7),
  selected_option smallint NOT NULL CHECK (selected_option BETWEEN 1 AND 4),
  is_correct boolean NOT NULL,
  answered_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT quiz_answers_slug_check CHECK (quiz_slug = 'quiz-aula-magna'),
  CONSTRAINT quiz_answers_session_question_key UNIQUE (session_id, question_number)
);
GRANT ALL ON public.quiz_answers TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.quiz_answers_id_seq TO service_role;
ALTER TABLE public.quiz_answers ENABLE ROW LEVEL SECURITY;

CREATE INDEX quiz_sessions_slug_started_idx ON public.quiz_sessions (quiz_slug, started_at DESC);
CREATE INDEX quiz_sessions_slug_completed_idx ON public.quiz_sessions (quiz_slug, completed_at DESC) WHERE completed_at IS NOT NULL;
CREATE INDEX quiz_answers_slug_question_answered_idx ON public.quiz_answers (quiz_slug, question_number, answered_at DESC);

CREATE OR REPLACE FUNCTION public.quiz_aula_magna_start(p_session_id uuid, p_quiz_slug text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
BEGIN
  IF p_session_id IS NULL OR p_quiz_slug IS DISTINCT FROM 'quiz-aula-magna' THEN
    RAISE EXCEPTION 'Invalid quiz session';
  END IF;

  INSERT INTO public.quiz_sessions (session_id, quiz_slug, last_question_reached)
  VALUES (p_session_id, p_quiz_slug, 1)
  ON CONFLICT (session_id) DO UPDATE
    SET last_activity_at = now()
    WHERE quiz_sessions.quiz_slug = EXCLUDED.quiz_slug;
END;
$function$;

CREATE OR REPLACE FUNCTION public.quiz_aula_magna_answer(
  p_session_id uuid,
  p_quiz_slug text,
  p_question_number integer,
  p_selected_option integer,
  p_is_correct boolean
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
BEGIN
  IF p_session_id IS NULL
     OR p_quiz_slug IS DISTINCT FROM 'quiz-aula-magna'
     OR p_question_number NOT BETWEEN 1 AND 7
     OR p_selected_option NOT BETWEEN 1 AND 4
     OR p_is_correct IS NULL THEN
    RAISE EXCEPTION 'Invalid quiz answer';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.quiz_sessions
    WHERE session_id = p_session_id AND quiz_slug = p_quiz_slug
  ) THEN
    RAISE EXCEPTION 'Quiz session not found';
  END IF;

  INSERT INTO public.quiz_answers (
    session_id, quiz_slug, question_number, selected_option, is_correct, answered_at
  ) VALUES (
    p_session_id, p_quiz_slug, p_question_number, p_selected_option, p_is_correct, now()
  )
  ON CONFLICT (session_id, question_number) DO UPDATE
    SET selected_option = EXCLUDED.selected_option,
        is_correct = EXCLUDED.is_correct,
        answered_at = EXCLUDED.answered_at
    WHERE quiz_answers.quiz_slug = EXCLUDED.quiz_slug;

  UPDATE public.quiz_sessions
  SET last_question_reached = GREATEST(last_question_reached, p_question_number),
      last_activity_at = now()
  WHERE session_id = p_session_id AND quiz_slug = p_quiz_slug;
END;
$function$;

CREATE OR REPLACE FUNCTION public.quiz_aula_magna_complete(
  p_session_id uuid,
  p_quiz_slug text,
  p_score integer
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
BEGIN
  IF p_session_id IS NULL
     OR p_quiz_slug IS DISTINCT FROM 'quiz-aula-magna'
     OR p_score NOT BETWEEN 0 AND 7 THEN
    RAISE EXCEPTION 'Invalid quiz completion';
  END IF;

  UPDATE public.quiz_sessions
  SET last_question_reached = 7,
      last_activity_at = now(),
      completed_at = COALESCE(completed_at, now()),
      score = p_score
  WHERE session_id = p_session_id AND quiz_slug = p_quiz_slug;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Quiz session not found';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.quiz_aula_magna_dashboard(p_password text, p_period text DEFAULT 'all')
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions, pg_temp
AS $function$
DECLARE
  v_from timestamptz;
  v_result jsonb;
  v_password_hash constant text := '$2y$12$ox4YtTDtiF6QCRylii6OketiMtlK2ZLC0xFMrtL0oqVuVfxApDV.u';
BEGIN
  IF p_password IS NULL OR crypt(p_password, v_password_hash) IS DISTINCT FROM v_password_hash THEN
    RAISE EXCEPTION 'Invalid dashboard password' USING ERRCODE = '42501';
  END IF;

  v_from := CASE p_period
    WHEN 'today' THEN date_trunc('day', now())
    WHEN '7d' THEN now() - interval '7 days'
    WHEN '30d' THEN now() - interval '30 days'
    WHEN 'all' THEN NULL
    ELSE NULL
  END;

  IF p_period NOT IN ('all', 'today', '7d', '30d') THEN
    RAISE EXCEPTION 'Invalid dashboard period';
  END IF;

  WITH filtered_sessions AS (
    SELECT * FROM public.quiz_sessions
    WHERE quiz_slug = 'quiz-aula-magna'
      AND (v_from IS NULL OR started_at >= v_from)
  ),
  filtered_answers AS (
    SELECT a.*
    FROM public.quiz_answers a
    JOIN filtered_sessions s ON s.session_id = a.session_id
    WHERE a.quiz_slug = 'quiz-aula-magna'
  ),
  numbers AS (
    SELECT generate_series(1, 7) AS question_number
  ),
  summary AS (
    SELECT
      count(*)::int AS starts,
      count(*) FILTER (WHERE completed_at IS NOT NULL)::int AS completions,
      COALESCE(round(100.0 * count(*) FILTER (WHERE completed_at IS NOT NULL) / NULLIF(count(*), 0), 1), 0) AS completion_rate,
      COALESCE(round(avg(score) FILTER (WHERE completed_at IS NOT NULL), 2), 0) AS average_score
    FROM filtered_sessions
  ),
  questions AS (
    SELECT n.question_number,
      (SELECT count(*)::int FROM filtered_sessions s WHERE s.last_question_reached >= n.question_number) AS reached,
      count(a.id)::int AS answers,
      COALESCE(round(100.0 * count(*) FILTER (WHERE a.selected_option = 1) / NULLIF(count(a.id), 0), 1), 0) AS option_a,
      COALESCE(round(100.0 * count(*) FILTER (WHERE a.selected_option = 2) / NULLIF(count(a.id), 0), 1), 0) AS option_b,
      COALESCE(round(100.0 * count(*) FILTER (WHERE a.selected_option = 3) / NULLIF(count(a.id), 0), 1), 0) AS option_c,
      COALESCE(round(100.0 * count(*) FILTER (WHERE a.selected_option = 4) / NULLIF(count(a.id), 0), 1), 0) AS option_d,
      COALESCE(round(100.0 * count(*) FILTER (WHERE a.is_correct) / NULLIF(count(a.id), 0), 1), 0) AS accuracy
    FROM numbers n
    LEFT JOIN filtered_answers a ON a.question_number = n.question_number
    GROUP BY n.question_number
    ORDER BY n.question_number
  ),
  stages AS (
    SELECT 0 AS stage_order, 'Início'::text AS label, (SELECT starts FROM summary) AS sessions
    UNION ALL
    SELECT n.question_number, 'Pergunta ' || n.question_number,
      (SELECT count(*)::int FROM filtered_answers a WHERE a.question_number = n.question_number)
    FROM numbers n
    UNION ALL
    SELECT 8, 'Conclusão', (SELECT completions FROM summary)
  ),
  funnel AS (
    SELECT stage_order, label, sessions,
      GREATEST(COALESCE(lag(sessions) OVER (ORDER BY stage_order), sessions) - sessions, 0)::int AS abandoned,
      COALESCE(round(100.0 * GREATEST(COALESCE(lag(sessions) OVER (ORDER BY stage_order), sessions) - sessions, 0)
        / NULLIF(lag(sessions) OVER (ORDER BY stage_order), 0), 1), 0) AS abandonment_rate
    FROM stages
  )
  SELECT jsonb_build_object(
    'summary', (SELECT to_jsonb(summary) FROM summary),
    'funnel', COALESCE((SELECT jsonb_agg(to_jsonb(funnel) - 'stage_order' ORDER BY stage_order) FROM funnel), '[]'::jsonb),
    'questions', COALESCE((SELECT jsonb_agg(to_jsonb(questions) ORDER BY question_number) FROM questions), '[]'::jsonb),
    'generated_at', now()
  ) INTO v_result;

  RETURN v_result;
END;
$function$;

REVOKE ALL ON FUNCTION public.quiz_aula_magna_start(uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.quiz_aula_magna_answer(uuid, text, integer, integer, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.quiz_aula_magna_complete(uuid, text, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.quiz_aula_magna_dashboard(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.quiz_aula_magna_start(uuid, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.quiz_aula_magna_answer(uuid, text, integer, integer, boolean) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.quiz_aula_magna_complete(uuid, text, integer) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.quiz_aula_magna_dashboard(text, text) TO anon, authenticated, service_role;